
POST http://debian:3001/api/login
Content-Type: application/json

{
  "username": "one",
  "password": "one"
}

###
POST http://debian:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9uZSIsImlkIjoiNjE5NjBhYTFhZTFjNmM3ODk2NzM4Y2ZlIiwiaWF0IjoxNjM3MjIzNTY1fQ.hw7jbks2hJ0IiE7bVQ39G-DqeKvcpc0sA6MX5pAwiQI


{
  "content": "87654678 note",
  "important": true
}


### creat user
POST http://debian:3001/api/users
content-type: application/json

{
  "username": "one",
  "password": "one"
}